

services:
  app:
    container_name: my_project_app
    build:
      context: .
    env_file:
      - .env-docker
    depends_on:
      - db
      - rabbitmq
    command: ["/src/for_docker/app.sh"]
    volumes:
      - ./app/doc_static/images:/app/doc_static/images
    ports:
      - "7777:8000"


  db:
    image: postgres:16
    container_name: my_project_postgres
    env_file:
      - .env-docker
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: my_project_rabbit
    hostname: rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"


  celery:
    build:
      context: .
    container_name: my_project_celery
    command: ["/src/for_docker/celery.sh"]
    volumes:
      - ./app/doc_static/images:/app/doc_static/images
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq

